### PR TITLE
setup tests

### PR DESCRIPTION
**Pull request by Binlogo**
Tests extracted from #1.

There are still issues to resolve. 🥺

After setting up all test fixtures and our DuckDB extension, we still cannot query the expected protobuf data. I'm not sure if I missed or misunderstood anything.

```sh
cargo test --workspace -- --nocapture

/protobuf.duckdb_extension --extension-version v0.0.1 --duckdb-version v1.0.0 --platform osx_arm64`
output generated "../../target/release/protobuf.duckdb_extension"
Metadata attached successfully.
test test_setup_creates_files ... ok
DuckDB extension loaded successfully.
Query result:
Query completed.
test test_query_protobuf_data ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.66s
```

For convenience, I have kept the `generated/` directory. I will delete and ignore it once the query issue is resolved.

@0xcaff, any assistance you could provide would be greatly appreciated.

### CODE REVIEW

**Comment by Binlogo** [comment]
By the way, I also tested using the CLI and received an empty query output as shown below:

```
D SELECT *
  FROM protobuf(
      descriptors = './tests/generated/descriptor.pb',
      files = './tests/generated/data/**/*.bin',
      message_type = 'user.User',
      delimiter = 'BigEndianFixed'
  )
  LIMIT 10;
┌─────────┬───────┬────────────┐
│  name   │  id   │ created at │
│ varchar │ int32 │ timestamp  │
├─────────┴───────┴────────────┤
│            0 rows            │
└──────────────────────────────
```

The good news is that the rows for protobuf and message_type seem to work.

**Comment by 0xcaff** [comment]
taking a look now!

**Comment by 0xcaff** [comment]
ok a couple things to note

duckdb_protobuf expects a stream of length delimited protobuf messages. With the query


```
SELECT *
  FROM protobuf(
      descriptors = './tests/generated/descriptor.pb',
      files = './tests/generated/data/**/*.bin',
      message_type = 'user.User',
      delimiter = 'BigEndianFixed'
  )
  LIMIT 10;
```

it expects files each with a sequence of

```
00 00 00 05     // length (a 4 byte big endian value)
xx xx xx xx xx   // 1st message bytes (5 bytes long as specified by previous field)
00 00 00 03     // length
xx xx xx            // 2nd message bytes (3 bytes long as specified by previous field)
```

This was done as many of the protobuf messages for my workload were quite tiny and I didn't want to deal with the overhead of the file system managing metadata for tens of millions of files. I guess I could make this more clear in the readme somewhere.

There are two possible length kinds https://github.com/0xcaff/duckdb_protobuf/blob/334dcce31925d3835eec2301f5800430217cf77e/packages/duckdb_protobuf/src/io.rs#L55-L58 the value can be specified as a varint also by using Varint for the delimiter value and varints in your input files (https://protobuf.dev/programming-guides/encoding/#varints).

Also, maybe its worthwhile adding a separate mode (probably configured by the delimiter option) which treats each file as a complete message.

Also, I think the errors could provide more information. i was thinking about how the file not found errors are not very clear and how its suboptimal before. will add something.

Does this make sense? Happy to write up the additional delimiter option if you will find it useful.

**Comment by 0xcaff** [comment]
Also thanks so much for digging through this and help me fill in the missing pieces. I really appreciate you taking the time to figure out how to use this thing and I hope it can help with whatever you're using it for.

**Comment by Binlogo** [comment]
Helps a lot and thanks for quick support for new message format.

**Comment by Binlogo** [comment]
After update to use 'SingleMessagePerFile', all tests passed 🎉. 

`cargo t --workspace -- --nocapture`

```
output generated "../../target/release/protobuf.duckdb_extension"
Metadata attached successfully.
test test_setup_creates_files ... ok
DuckDB extension loaded successfully.
Query result: [("Alice", 1), ("Bob", 2), ("Charlie", 3)]
test test_query_protobuf_data ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.80s
```

**Comment by 0xcaff** [comment]
thanks so much for your contribution! let me know if you find anything else unclear or suboptimal. I'll get this merged in soon (want to think a little bit about making the build step a bit less kludgy first).

**Comment by Binlogo** [comment]
Thanks for merging. ❤️

**Pull request merged**
